language: generic
sudo: required
services:
  - docker

  before_install:
    - docker build -t bmadjidi/docker-react -f Dockerfile.dev .

  script:
    - docker run bmadjidi/docker-react npm run test -- --coverage